#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    autonSelect,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  floor,          sensorTouch)
#pragma config(Sensor, dgtl2,  LDrive,         sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  RDrive,         sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  launcherValue,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightLauncher1, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightLauncher4, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightLauncher3, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightLauncher2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftLauncher3, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftLauncher2, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftLauncher4, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftLauncher1, tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

bool raiseStarOffGround = false;
bool lifting = false;

void resetEncoders(){
	SensorValue(LDrive) = 0;
	SensorValue(RDrive) = 0;
}

void setLeftLauncher(int speed){
	motor[leftLauncher1] = speed;
	motor[leftLauncher2] = speed;
	motor[leftLauncher3] = speed;
	motor[leftLauncher4] = speed;
}

void setRightLauncher(int speed){
	motor[rightLauncher1] = speed;
	motor[rightLauncher2] = speed;
	motor[rightLauncher3] = speed;
	motor[rightLauncher4] = speed;
}

void setLauncher(int speed){
	setRightLauncher(speed);
	setLeftLauncher(speed);
}

void setLeftDrive(int speed){
	motor[leftDrive] = speed;
}

void setRightDrive(int speed){
	motor[rightDrive] = speed;
}

void setDrive(int speed){
	setRightDrive(speed);
	setLeftDrive(speed);
}


void raiseLauncher(int value){
	while(SensorValue(launcherValue) > -value){
		setLauncher(70);
	}
	setLauncher(10);
}

void turnLeftFor(int value){
	resetEncoders();
	while(SensorValue(LDrive) > -value || SensorValue(RDrive) < value){
		if(SensorValue(LDrive) > -value){
			setLeftDrive(-70);
		}
		else{
			setLeftDrive(0);
		}

		if(SensorValue(RDrive) < value){
			setRightDrive(70);
		}
		else{
			setRightDrive(0);
		}
	}
	setDrive(0);
}

void turnRightFor(int value){
	resetEncoders();
	while(SensorValue(RDrive) > -value || SensorValue(LDrive) < value){
		if(SensorValue(RDrive) > -value){
			setRightDrive(-70);
		}
		else
			setRightDrive(0);

		if(SensorValue(LDrive) < value){
			setLeftDrive(70);
		}
		else
			setLeftDrive(0);
	}
	setDrive(0);
}

void driveForwardFor(int value){
	resetEncoders();
	while(SensorValue(RDrive) < value || SensorValue(LDrive) < value){
		if(SensorValue(RDrive) < value){
			setRightDrive(70);
		}
		else
			setRightDrive(0);
		if(SensorValue(LDrive) < value){
			setLeftDrive(70);
		}
		else
			setLeftDrive(0);
	}
	setDrive(0);
}

void driveBackwardFor(int value){
	resetEncoders();
	while(SensorValue(RDrive) > -value || SensorValue(LDrive) > -value){
		if(SensorValue(RDrive) > -value){
			setRightDrive(-70);
		}
		else
			setRightDrive(0);

		if(SensorValue(LDrive) > -value){
			setLeftDrive(-70);
		}
		else
			setLeftDrive(0);
	}
	setDrive(0);
}

void launcherAuto(){
	if(raiseStarOffGround){
		if(SensorValue(launcherValue) > -200){
			setLauncher(70);
		}
		else{
			setLauncher(15);
		}
	}
}

void misc(){
	if(vexRT[Btn8D]){
		raiseStarOffGround = true;
	}
}

void driver(){
	if(abs(vexRT[Ch3]) > 10){
		setLeftDrive(vexRT[Ch3]);
	}
	else{
		setLeftDrive(0);
	}

	if(abs(vexRT[Ch2]) > 10){
		setRightDrive(vexRT[Ch2]);
	}
	else{
		setRightDrive(vexRT[Ch2]);
	}
}

void launcher(){
	if(vexRT[Btn6U] && SensorValue(launcherValue) > -500){
		setLauncher(127);
		raiseStarOffGround = false;
		lifting = false;
	}
	else if(vexRT[Btn6D]){
		setLauncher(-40);
		raiseStarOffGround = false;
		lifting = false;
	}
	else{
		if(!lifting){
			if(SensorValue(launcherValue) <= -100 && !raiseStarOffGround){
				setLauncher(15);
			}
			else{
				if(!raiseStarOffGround){
					setLauncher(0);
				}
			}
		}

		if(vexRT[Btn5D]){
			setLauncher(-60);
			lifting = true;
			raiseStarOffGround = false;
		}
		else if(vexRT[Btn5U]){
			setLauncher(-127);
			lifting = true;
			raiseStarOffGround = false;
		}
		else if(lifting)
			setLauncher(0);
	}
}

void defliporlift(){
	if(vexRT[Btn6U]){
		setLauncher(127);
	}
	else if(vexRT[Btn6D]){
		setLauncher(-127);
	}
	else{
		setLauncher(0);
	}
}

void halfLift(){
	if(vexRT[Btn6U]){
		setLauncher(127);
	}
	else if(vexRT[Btn6D]){
		setLauncher(-60);
	}
	else{
		setLauncher(0);
	}
}




/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton(){
	SensorValue(launcherValue) = 0;
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  resetEncoders();



	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous(){
	resetEncoders();
	if(SensorValue(autonSelect) < 1500){
		resetEncoders();
		driveForwardFor(300);
		raiseLauncher(100);
		driveForwardFor(400);
		delay(100);
		turnRightFor(220);
		delay(100);
		//driveBackwardFor(1600);
		delay(100);
		setDrive(-127);
		delay(3000);
		setDrive(0);
		delay(100);
		raiseLauncher(300);
		delay(00);
		setLauncher(-40);
		delay(250);
		setLauncher(15);
		delay(100);
		driveForwardFor(720);
		delay(100);
		//raiseLauncher(400);
		delay(100);
		//setLauncher(-40);
		delay(150);
		//setLauncher(15);
		delay(100);
	}
	else if(SensorValue(autonSelect) >= 1500 && SensorValue(autonSelect) <= 2500){

		setDrive(70);
		delay(4000);
		setDrive(0);
	}
	else if(SensorValue(autonSelect) > 2500){

		setDrive(127);
		delay(1000);
		setDrive(-15);
		delay(100);
		setDrive(0);
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol(){
  while (true){
		driver();
		/*
		if(vexRT[Btn7U]){
			defliporlift();
		}
		else if(vexRT[Btn7L]){
			halfLift();
		}
		else{
		*/
			launcher();
		//}
		misc();
		launcherAuto();
  }
}
