#pragma config(Sensor, in1,    autonSelect,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  lockStop,       sensorTouch)
#pragma config(Sensor, dgtl2,  leftTensionerZero, sensorTouch)
#pragma config(Sensor, dgtl3,  righttTensionerZero, sensorTouch)
#pragma config(Sensor, dgtl4,  leftTensionerPos, sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  rightTensionerPos, sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  leftDrivePos,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10, rightDrivePos,  sensorQuadEncoder)
#pragma config(Sensor, dgtl12, launcherPos,    sensorQuadEncoder)
#pragma config(Motor,  port2,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           rightLauncher, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           release,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftLauncher,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightRear,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftRear,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define launcherDelay 500

string armState = "tensioned";
bool manual = false;
bool brake = false;
int currentTime = 0;
int timeLaunched = 0;
bool alreadyStamped = false;
int target = 1;
void partnerControls(){
	if(vexRT[Btn6DXmtr2])
			motor[rightLauncher] = 127;
		else if(vexRT[Btn6UXmtr2])
			motor[rightLauncher] = -127;
		else{
			if(brake)
				motor[rightLauncher] = 10;
			else
				motor[rightLauncher] = 0;
		}

		if(vexRT[Btn5DXmtr2])
			motor[leftLauncher] = 127;
		else if(vexRT[Btn5UXmtr2])
			motor[leftLauncher] = -127;
		else{
			if(brake)
				motor[leftLauncher] = 10;
			else
				motor[leftLauncher] = 0;
		}

		if(vexRT[Btn8UXmtr2])
			motor[release] = 127;
		else if(vexRT[Btn8DXmtr2])
			motor[release] = -127;
		else
			motor[release] = 0;

		if(vexRT[Btn7LXmtr2])
			brake = true;
		else if(vexRT[Btn7RXmtr2])
			brake = false;

}

void updateTime(){
	if(armState == "LaunchedAuto" && !alreadyStamped){
		timeLaunched = currentTime;
	}
	else if(alreadyStamped && (currentTime - timeLaunched) >= launcherDelay){
		armState = "lowering";
		alreadyStamped = false;
	}
}

void setLeftTensioner(int power)
{
	motor[leftLauncher] = power;
	//motor[tensionerLeft2] = power;
}
void setRightTensioner(int power)
{
	motor[rightLauncher] = power;
	//motor[tensionerRight2] = power;
}
void setTensioner(int power)
{
	setLeftTensioner(power);
	setRightTensioner(power);
}
void setLeftDrive(int power)
{
	motor[leftFront] = power;
	motor[leftRear] = power;
}
void setRightDrive(int power)
{
	motor[rightFront] = power;
	motor[rightRear] = power;
}
void setDrive(int power)
{
	setLeftDrive(power);
	setRightDrive(power);
}
void getTensionerPos(){

}
void updateTensioner()
{
	if(armState == "tensioned" || armState == "tensioning"){
		if(SensorValue(leftTensionerPos) > (target - 10) && SensorValue(leftTensionerPos) < (target + 10)){
			setLeftTensioner(15);
		}
		else if(SensorValue(leftTensionerPos) < (target - 10)){
			setLeftTensioner(127);
		}
		if(SensorValue(rightTensionerPos) > (target - 10) && SensorValue(rightTensionerPos) < (target + 10)){
			setRightTensioner(15);
		}
		else if(SensorValue(rightTensionerPos) < (target - 10)){
			setRightTensioner(127);
		}
		if((SensorValue(leftTensionerPos) > (target - 10) && SensorValue(leftTensionerPos) < (target + 10)) && (SensorValue(rightTensionerPos) > (target - 10) && SensorValue(rightTensionerPos) < (target + 10))){
			armState = "tensioned";
		}
	}
	else if(armState == "launched"){
		if(SensorValue(leftTensionerPos) <= 0){
			setLeftTensioner(0);
		}
		else if(SensorValue(leftTensionerPos) > 0){
			setLeftTensioner(-127);
		}
		if(SensorValue(rightTensionerPos) <= 0){
			setRightTensioner(0);
		}
		else if(SensorValue(rightTensionerPos) > 0){
			setRightTensioner(-127);
		}
		if((SensorValue(leftTensionerPos) <= 0) && (SensorValue(rightTensionerPos) <= 0)){
			armState = "down"
		}
	}
}
void updateDrive()
{
	if(abs(vexRT[Ch3]) > 10)
	{
		setLeftDrive(vexRT[Ch3]);
	}
	else
	{
		setLeftDrive(0);
	}
	if(abs(vexRT[Ch2]) > 10)
	{
		setRightDrive(vexRT[Ch2]);
	}
	else
	{
		setRightDrive(0);
	}
}
void getInput()
{
	if(!manual)
	{
		if(vexRT[Btn8D])
		{
			if(armState == "tensioned")
			{
				armState = "launching";
			}
			else if(armState == "launching" || armState == "launchedAuto" || armState == "tensioning" || armState == "lowering")
			{
				//Do nothing
			}
			else if(armState == "launchedManual")
			{
				armState = "lowering";
			}
		}
		if(vexRT[Btn8U])
		{
			if(armState == "launching" || armState == "tensioned" || armState == "tensioning" || armState == "lowering" || armState == "launchedAuto" ||
				armState == "launchingAuto")
			{
				armState = "launchingManual";
			}
		}
	}
	else{
		partnerControls();
	}

}

task main()
{
	while(true)
	{
		updateTime();
		currentTime++;

		updateDrive();
		getInput();

		delay(10);
	}
}
